def check(value):
	if not value:
		raise Exception("test failed")